apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
  namespace: default
spec:
  containers:
  - name: privileged-container
    image: busybox
    command: ["sh", "-c", "sleep 9999"]
    securityContext:
      privileged: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.5"
      requests:
        memory: "64Mi"
        cpu: "0.25"
---
apiVersion: v1
kind: Service
metadata:
  name: privileged-service
  namespace: default
spec:
  selector:
    app: privileged-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
